### ISSUE TITLE
Why 666?

### ISSUE THREAD

**Issue by suntong** [mh-cbon/666#2]
Why it called 666? Such a strange name.

**Comment by mh-cbon** [comment]
why not ?

It s the sign of the beast, according to the religion, 
those marked by it are evil,

That program marks the program completion 
with a success/error message.

Obviously if one believes in such signs for real....

Its all MIT, DIY if you don t like it, make your own.

**Comment by suntong** [comment]
k. Not to question you, just wanted to know. thx.

**Comment by mh-cbon** [comment]
yep sure
